name: Build and deploy Node.js app to Azure Web App - SafeHaven2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install
        run: |
          cd packages/express-backend
          npm install
          npm install multer
          npm install jsonwebtoken
          npm install bcrypt
          cd ../../

  zip-and-upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: packages/express-backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app   
          path: packages/express-backend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: zip-and-upload
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F78BFACEB8754DF0B3920B38D34A736F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DB909594BB3047A0814E70CF6073DBB2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_608B604CBDDF458FBBD38EB943ADE02F }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SafeHaven2'
          slot-name: 'Production'
          package: .
          configuration-files: 'web.config'
