name: CI
on:
  push:
    branches: ["Develop"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 🏗️ Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: ⎔ Setup Node
        uses: actions/setup-node@v3
        with:
          cache: "npm"
        run: npm ci
        
      - name: 📦 Build app
        run: npm run build
        
      - name: 📏 Check for code style compliance
        run: npm run eslint
        
      - name: 🧪 Run tests
        run: npm run test
        
